### ISSUE TITLE
No ArgoCD diff on self hosted variant

### ISSUE THREAD

**Issue by FlorisFeddema** [infro-io/infro-core#4]
I have tried to deploy the self hosted version on Kubernetes on my homelab. (https://github.com/FlorisFeddema/homelab/tree/main/products/infro)

It places a comment on my github pull requests but does not show a diff. There are also no error logs about this. (https://github.com/FlorisFeddema/homelab/pull/866#issuecomment-2067714716)

Used config:
```
deployers:
  - type: argocd
    name: homelab
    endpoint: argocd.feddema.dev:443
    authtoken: redacted
vcs:
  type: github
  authtoken: ### redacted
```
